---
apiVersion: v1
kind: Service
metadata:
  name: web-traefik
  namespace: kube-system
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-web-traefik
  namespace: kube-system
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-traefik
            port:
              number: 80

