# -*- mode: ruby -*-
# vi: set ft=ruby :
#
#
Vagrant.require_version ">= 1.7.0"

nodes = 2

Vagrant.configure("2") do |config|
  
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false
  # Ensure that all the vagrant machines use the same SSH pair. From 1.7.0 this is by default true
  config.ssh.insert_key = true
  config.ssh.keys_only = true

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.define "admin" do |admin|
    admin.vm.network "private_network", ip: "192.168.56.100"
    admin.vm.hostname = "admin"

    admin.vm.provider "virtualbox" do |vb|
      vb.gui = false
      # Name which appears at the virtualbox GUI
      vb.name = "kubeadm"
      vb.memory = 8192
      vb.cpus = 2
    end

    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    admin.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = {
        ip_address: "192.168.56.100"
      }
    end
  end

  (1..nodes).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.network "private_network", ip: "192.168.56.#{100 + i}"
      node.vm.hostname = "node#{i}"

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        # Name which appears at the virtualbox GUI
        vb.name = "node#{i}"
        vb.memory = 2024 
        vb.cpus = 1
      end

      # Enable provisioning with a shell script. Additional provisioners such as
      # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
      # documentation for more information about their specific syntax and use.
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "node-playbook.yml"
      end
    end
  end 
end
